### PR TITLE
Fix: check eslint on github actions

### PR DESCRIPTION
**Pull request by phanlyhuynh**
@DemonDaddy22 Hi. I fixed it, issue https://github.com/DemonDaddy22/all-about-reactJS/issues/5 . Can you check for me? Thanks!!!

### CODE REVIEW

**Review by DemonDaddy22 — APPROVED** [review]

**Comment by DemonDaddy22** [comment]
@phanlyhuynh I've merged this, will test it tomorrow and check if it's working fine now.

**Comment by DemonDaddy22** [comment]
@all-contributors please add @phanlyhuynh for code

**Comment by DemonDaddy22** [comment]
@phanlyhuynh  What commands are you running to check if this is working?
Because there still seems to be some issue when I'm doing it.
Screenshot 2020-10-12 at 1 04 52 PM

**Comment by phanlyhuynh** [comment]
In my pull request:
image
but in master branch:
image

and fix `eslint src/` to `./node_modules/.bin/eslint src/`. I tested on another repo. You don't need to revert, i will create new pull request and fix it. Thansk!
Update: I fixed it, https://github.com/DemonDaddy22/all-about-reactJS/pull/29. Thanks!

**Comment by DemonDaddy22** [comment]
I removed eslint from devDependencies as it was giving an issue in build, as there was a mismatch in version.
Screenshot 2020-10-12 at 5 00 48 PM

**Comment by phanlyhuynh** [comment]
@DemonDaddy22 You can remove node_modules, package-lock.json, yarn.lock then run `yarn` or `npm install`. it will resolve!!!

**Comment by DemonDaddy22** [comment]
@phanlyhuynh There's an issue with the linting, I don't know if there's an issue with the version, because it is giving errors for ES6 syntax too. These things should not come up as errors.
Screenshot 2020-10-12 at 5 29 43 PM
Screenshot 2020-10-12 at 5 34 40 PM

**Comment by phanlyhuynh** [comment]
@DemonDaddy22 I will edit `.eslintrc.js`:
```
...
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true,
            "modules": true,
            "experimentalObjectRestSpread": true
        }
    },
...
```
then install `babel-eslint`, command `yarn add -D babel-eslint`. it will resolve, you can test it in locally

**Comment by DemonDaddy22** [comment]
Sure, after adding this, please run the same on your local too and share the screenshot, so I can double check if it is not giving errors for jsx and ES6 syntax.

**Comment by phanlyhuynh** [comment]
@DemonDaddy22 
image

image

image

image

image

**Comment by DemonDaddy22** [comment]
These aren't errors actually, for example, localStorage and document are valid JS variables and this is giving them as errors. Also, it shouldn't point out errors for not specifying prop-types.
The only errors should be syntax errors, unused imports.

Maybe this will act as a [reference](https://dev.to/devdammak/setting-up-eslint-in-your-javascript-project-with-vs-code-2amf).

**Comment by phanlyhuynh** [comment]
@DemonDaddy22 Tomorrow, i will fix it 👍

**Pull request merged**
